# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=make
CC=gcc
GCC_MAJOR=3
HOST_CC=gcc
AR=ar
CFLAGS=-O2
LDFLAGS=
EXE=
EXTRALIBS=-lm
VERSION=0.3.2dev
CONFIG_NETWORK=yes
CONFIG_DLL=yes
SRC_PATH=/Users/robrohan/Projects/qi
