# by default, plugins are copied in ~/.qi/ so that Qi can load it automatically.
all: 
	@echo " == example == "
	make -C example all

install: 
	make -C example install

clean:
	make -C example clean
