name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --cc=gcc
    - name: test
      run: make test
    - name: build
      run: make clean qi

    - uses: actions/checkout@v2
    - name: cppcheck
      uses: deep5050/cppcheck-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        enable: warning,style,performance,portability,information,unusedFunction
        force_language: c
