name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Test
      run: ./configure --cc=gcc; make test; ./build/run_tests
    - name: Build
      run: ./configure --cc=gcc; make clean qi
    - name: Tiny Build
      run: ./configure --cc=gcc --enable-tiny; make clean qi

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Test
      run: ./configure --cc=clang; make test; ./build/run_tests
    - name: Build
      run: ./configure --cc=clang; make clean qi

#    - name: cppcheck
#      uses: deep5050/cppcheck-action@main
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        enable: warning,style,performance,portability,information,unusedFunction
#        force_language: c
